import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './common.css'
import './fancy.css'
import { ChatSettingsProvider } from '@/providers/chat-settings-provider/chat-settings-provider'
import { TranslateSettingsProvider } from '@/providers/translate-settings-provider/translate-settings-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TranslateSettingsProvider>
          <ChatSettingsProvider>
            {children}
          </ChatSettingsProvider>
        </TranslateSettingsProvider>
      </body>
    </html>
  )
}
